### ISSUE TITLE
关于RT-AK支持的cubemx ai版本问题

### ISSUE THREAD

**Issue by addw1** [RT-Thread/RT-AK#18]
您好，想问一下RT-AK支持到cubemx ai的哪一个版本了，6.0.0可以用吗？谢谢

**Comment by pinxue** [comment]
目前支持的是 5.2.0 版本，详见 https://github.com/RT-Thread/RT-AK-plugin-stm32 。后续请在插件仓库讨论。

**Comment by addw1** [comment]
好的谢谢

**Comment by pinxue** [comment]
FYI 7.0 版本的支持已经合并了
https://github.com/RT-Thread/RT-AK-plugin-stm32/pull/7
