### ISSUE TITLE
模型输出怎么转化成浮点数

### ISSUE THREAD

**Issue by Lizvx** [RT-Thread/RT-AK#19]
模型只有5个分类，由于输出的是浮点数，所以每个数据占据4个字节，但是模型输出变成了20个整型，如何使其正确的输出浮点数

**Comment by Lebhoryi** [comment]
用的是 STM32 还是 K210

**Comment by QiwenLi0729** [comment]
RT-AK框架接口定义buffer统一是uint8_t*。模型计算结果通常是浮点输出存放在buffer中。由一个uint8_t* 指针指向, 然后根据需求进行类型转换.

**Comment by pinxue** [comment]
@Lzvx 问题是否已经解决？

**Comment by pinxue** [comment]
假设是解决了。如果还有问题可再打开本议题。
