### ISSUE TITLE
ide 安装k210 sdk 失败 切换安装源没用

### ISSUE THREAD

**Issue by linuszp** [RT-Thread/RT-AK#26]

**Comment by yc66542260** [comment]
Firstly, if you are in mainland of China, please make sure your installation source is gitee, because sometimes github doesn't work. Secondly, update your rt-studio IDE to keep it is the latest revision. Thirdly, try to click the download button more times, somtimes it works. Good luck~

**Comment by yc66542260** [comment]
Any other question, feel free to ask me

**Comment by pinxue** [comment]
长久没有活动，先关闭了。
